import "server-only";
import type { GuestRow } from "./schema";

// AUTO-GENERATED from the "Guests" Google Sheet. Do not edit by hand.
// Re-sync after editing the sheet with:  npm run sync-guests
//
// IMPORTANT: order MUST match the sheet's row order. rowIndex is derived from
// position below (the sheet header is row 1, so the first guest here is row 2),
// and the RSVP writer targets G{rowIndex}:K{rowIndex} in the sheet.
export const GUEST_ROSTER: Omit<GuestRow, "rowIndex">[] = [
  { partyId: "P-001", partyLabel: "The Krauses (Michael)", firstName: "Michael", lastName: "Krause", relationship: "primary", side: "bride" },
  { partyId: "P-001", partyLabel: "The Krauses (Michael)", firstName: "Stephanie", lastName: "Krause", relationship: "spouse", side: "bride" },
  { partyId: "P-001", partyLabel: "The Krauses (Michael)", firstName: "Chloe", lastName: "Krause", relationship: "plus-one", side: "bride" },
  { partyId: "P-002", partyLabel: "Sydney Krause", firstName: "Sydney", lastName: "Krause", relationship: "primary", side: "bride" },
  { partyId: "P-003", partyLabel: "Joseph Krause & Kenzie Murdoch", firstName: "Joseph", lastName: "Krause", relationship: "primary", side: "bride" },
  { partyId: "P-003", partyLabel: "Joseph Krause & Kenzie Murdoch", firstName: "Kenzie", lastName: "Murdoch", relationship: "spouse", side: "bride" },
  { partyId: "P-004", partyLabel: "Shirley Krause", firstName: "Shirley", lastName: "Krause", relationship: "primary", side: "bride" },
  { partyId: "P-005", partyLabel: "The Hoartys (Vicki)", firstName: "Vicki", lastName: "Hoarty", relationship: "primary", side: "bride" },
  { partyId: "P-005", partyLabel: "The Hoartys (Vicki)", firstName: "Tim", lastName: "Hoarty", relationship: "spouse", side: "bride" },
  { partyId: "P-006", partyLabel: "The Hoartys (Dylan)", firstName: "Dylan", lastName: "Hoarty", relationship: "primary", side: "bride" },
  { partyId: "P-006", partyLabel: "The Hoartys (Dylan)", firstName: "Jessica", lastName: "Hoarty", relationship: "spouse", side: "bride" },
  { partyId: "P-006", partyLabel: "The Hoartys (Dylan)", firstName: "Nova", lastName: "Hoarty", relationship: "child", side: "bride" },
  { partyId: "P-007", partyLabel: "The Joneses", firstName: "Connie", lastName: "Jones", relationship: "primary", side: "bride" },
  { partyId: "P-007", partyLabel: "The Joneses", firstName: "Doug", lastName: "Jones", relationship: "spouse", side: "bride" },
  { partyId: "P-008", partyLabel: "The Reinsches (Travis)", firstName: "Travis", lastName: "Reinsch", relationship: "primary", side: "bride" },
  { partyId: "P-008", partyLabel: "The Reinsches (Travis)", firstName: "Aftan", lastName: "Reinsch", relationship: "spouse", side: "bride" },
  { partyId: "P-008", partyLabel: "The Reinsches (Travis)", firstName: "Hazel", lastName: "Reinsch", relationship: "child", side: "bride" },
  { partyId: "P-008", partyLabel: "The Reinsches (Travis)", firstName: "Fox", lastName: "Reinsch", relationship: "child", side: "bride" },
  { partyId: "P-009", partyLabel: "The Lefevers", firstName: "Chelsey", lastName: "Lefever", relationship: "primary", side: "bride" },
  { partyId: "P-009", partyLabel: "The Lefevers", firstName: "Nate", lastName: "Lefever", relationship: "spouse", side: "bride" },
  { partyId: "P-009", partyLabel: "The Lefevers", firstName: "Cooper", lastName: "Lefever", relationship: "child", side: "bride" },
  { partyId: "P-009", partyLabel: "The Lefevers", firstName: "Hudson", lastName: "Lefever", relationship: "child", side: "bride" },
  { partyId: "P-009", partyLabel: "The Lefevers", firstName: "Lawson", lastName: "Lefever", relationship: "child", side: "bride" },
  { partyId: "P-009", partyLabel: "The Lefevers", firstName: "Piper", lastName: "Lefever", relationship: "child", side: "bride" },
  { partyId: "P-010", partyLabel: "The Reinsches (Tyson)", firstName: "Tyson", lastName: "Reinsch", relationship: "primary", side: "bride" },
  { partyId: "P-010", partyLabel: "The Reinsches (Tyson)", firstName: "May", lastName: "Reinsch", relationship: "spouse", side: "bride" },
  { partyId: "P-011", partyLabel: "Marilyn Krause", firstName: "Marilyn", lastName: "Krause", relationship: "primary", side: "bride" },
  { partyId: "P-012", partyLabel: "The Krauses (Gerad)", firstName: "Gerad", lastName: "Krause", relationship: "primary", side: "bride" },
  { partyId: "P-012", partyLabel: "The Krauses (Gerad)", firstName: "Tara", lastName: "Krause", relationship: "spouse", side: "bride" },
  { partyId: "P-013", partyLabel: "The Krauses (Nick)", firstName: "Nick", lastName: "Krause", relationship: "primary", side: "bride" },
  { partyId: "P-013", partyLabel: "The Krauses (Nick)", firstName: "Kerry", lastName: "Krause", relationship: "spouse", side: "bride" },
  { partyId: "P-013", partyLabel: "The Krauses (Nick)", firstName: "Rowan", lastName: "Krause", relationship: "child", side: "bride" },
  { partyId: "P-013", partyLabel: "The Krauses (Nick)", firstName: "Miles", lastName: "Krause", relationship: "child", side: "bride" },
  { partyId: "P-013", partyLabel: "The Krauses (Nick)", firstName: "Remi", lastName: "Krause", relationship: "child", side: "bride" },
  { partyId: "P-014", partyLabel: "The Nances", firstName: "Ashley", lastName: "Nance", relationship: "primary", side: "bride" },
  { partyId: "P-014", partyLabel: "The Nances", firstName: "Zuri", lastName: "Nance", relationship: "spouse", side: "bride" },
  { partyId: "P-014", partyLabel: "The Nances", firstName: "Millie", lastName: "Nance", relationship: "child", side: "bride" },
  { partyId: "P-014", partyLabel: "The Nances", firstName: "Marla", lastName: "Nance", relationship: "child", side: "bride" },
  { partyId: "P-015", partyLabel: "Barb Jansen", firstName: "Barb", lastName: "Jansen", relationship: "primary", side: "bride" },
  { partyId: "P-016", partyLabel: "The Ruhls", firstName: "Ryan", lastName: "Ruhl", relationship: "primary", side: "bride" },
  { partyId: "P-016", partyLabel: "The Ruhls", firstName: "Kristen", lastName: "Ruhl", relationship: "spouse", side: "bride" },
  { partyId: "P-016", partyLabel: "The Ruhls", firstName: "Payton", lastName: "Ruhl", relationship: "plus-one", side: "bride" },
  { partyId: "P-017", partyLabel: "Erin Jansen & Aliya Awadey", firstName: "Erin", lastName: "Jansen", relationship: "primary", side: "bride" },
  { partyId: "P-017", partyLabel: "Erin Jansen & Aliya Awadey", firstName: "Aliya", lastName: "Awadey", relationship: "spouse", side: "bride" },
  { partyId: "P-018", partyLabel: "Deborah Lewis", firstName: "Deborah", lastName: "Lewis", relationship: "primary", side: "bride" },
  { partyId: "P-019", partyLabel: "The Schaudels", firstName: "Wanda", lastName: "Schaudel", relationship: "primary", side: "bride" },
  { partyId: "P-019", partyLabel: "The Schaudels", firstName: "George", lastName: "Schaudel", relationship: "spouse", side: "bride" },
  { partyId: "P-019", partyLabel: "The Schaudels", firstName: "Riley", lastName: "Schaudel", relationship: "plus-one", side: "bride" },
  { partyId: "P-020", partyLabel: "John Austin Schaudel", firstName: "John Austin", lastName: "Schaudel", relationship: "primary", side: "bride" },
  { partyId: "P-021", partyLabel: "Cade Schaudel", firstName: "Cade", lastName: "Schaudel", relationship: "primary", side: "bride" },
  { partyId: "P-022", partyLabel: "Scott Meyer", firstName: "Scott", lastName: "Meyer", relationship: "primary", side: "bride" },
  { partyId: "P-023", partyLabel: "Barbara Meyer", firstName: "Barbara", lastName: "Meyer", relationship: "primary", side: "bride" },
  { partyId: "P-024", partyLabel: "The Bremmers", firstName: "Lynn", lastName: "Bremmer", relationship: "primary", side: "bride" },
  { partyId: "P-024", partyLabel: "The Bremmers", firstName: "Robert", lastName: "Bremmer", relationship: "spouse", side: "bride" },
  { partyId: "P-025", partyLabel: "The Lewans", firstName: "Rachel", lastName: "Lewan", relationship: "primary", side: "bride" },
  { partyId: "P-025", partyLabel: "The Lewans", firstName: "Michael", lastName: "Lewan", relationship: "spouse", side: "bride" },
  { partyId: "P-026", partyLabel: "Rebekah Bremmer", firstName: "Rebekah", lastName: "Bremmer", relationship: "primary", side: "bride" },
  { partyId: "P-027", partyLabel: "Dee Nunnick & Sam Sexton", firstName: "Dee", lastName: "Nunnick", relationship: "primary", side: "bride" },
  { partyId: "P-027", partyLabel: "Dee Nunnick & Sam Sexton", firstName: "Sam", lastName: "Sexton", relationship: "spouse", side: "bride" },
  { partyId: "P-028", partyLabel: "The Matteses", firstName: "Matt", lastName: "Mattes", relationship: "primary", side: "bride" },
  { partyId: "P-028", partyLabel: "The Matteses", firstName: "Melanie", lastName: "Mattes", relationship: "spouse", side: "bride" },
  { partyId: "P-029", partyLabel: "Ryan Mattes & Meridith Graves", firstName: "Ryan", lastName: "Mattes", relationship: "primary", side: "bride" },
  { partyId: "P-029", partyLabel: "Ryan Mattes & Meridith Graves", firstName: "Meridith", lastName: "Graves", relationship: "spouse", side: "bride" },
  { partyId: "P-030", partyLabel: "The Hoods", firstName: "Robin", lastName: "Hood", relationship: "primary", side: "bride" },
  { partyId: "P-030", partyLabel: "The Hoods", firstName: "Kevin", lastName: "Hood", relationship: "spouse", side: "bride" },
  { partyId: "P-031", partyLabel: "Debbie Moeller", firstName: "Debbie", lastName: "Moeller", relationship: "primary", side: "bride" },
  { partyId: "P-032", partyLabel: "The Collinses", firstName: "Kathy", lastName: "Collins", relationship: "primary", side: "bride" },
  { partyId: "P-032", partyLabel: "The Collinses", firstName: "Jeff", lastName: "Collins", relationship: "spouse", side: "bride" },
  { partyId: "P-033", partyLabel: "The Schoeglers", firstName: "Maddie", lastName: "Schoegler", relationship: "primary", side: "bride" },
  { partyId: "P-033", partyLabel: "The Schoeglers", firstName: "Alex", lastName: "Schoegler", relationship: "spouse", side: "bride" },
  { partyId: "P-034", partyLabel: "The Olivers", firstName: "Jill", lastName: "Oliver", relationship: "primary", side: "bride" },
  { partyId: "P-034", partyLabel: "The Olivers", firstName: "Robert", lastName: "Oliver", relationship: "spouse", side: "bride" },
  { partyId: "P-035", partyLabel: "The Gossicks", firstName: "Allison", lastName: "Gossick", relationship: "primary", side: "bride" },
  { partyId: "P-035", partyLabel: "The Gossicks", firstName: "Doug", lastName: "Gossick", relationship: "spouse", side: "bride" },
  { partyId: "P-035", partyLabel: "The Gossicks", firstName: "Jackson", lastName: "Gossick", relationship: "plus-one", side: "bride" },
  { partyId: "P-035", partyLabel: "The Gossicks", firstName: "Camryn", lastName: "Gossick", relationship: "plus-one", side: "bride" },
  { partyId: "P-035", partyLabel: "The Gossicks", firstName: "Ryan", lastName: "Gossick", relationship: "plus-one", side: "bride" },
  { partyId: "P-036", partyLabel: "Connie Ross", firstName: "Connie", lastName: "Ross", relationship: "primary", side: "bride" },
  { partyId: "P-037", partyLabel: "Mary Martell", firstName: "Mary", lastName: "Martell", relationship: "primary", side: "bride" },
  { partyId: "P-038", partyLabel: "Lori Lassman & David O'hara", firstName: "Lori", lastName: "Lassman", relationship: "primary", side: "bride" },
  { partyId: "P-038", partyLabel: "Lori Lassman & David O'hara", firstName: "David", lastName: "O'hara", relationship: "spouse", side: "bride" },
  { partyId: "P-039", partyLabel: "Caroline Lassman", firstName: "Caroline", lastName: "Lassman", relationship: "primary", side: "bride" },
  { partyId: "P-040", partyLabel: "The Laufers", firstName: "Kristin", lastName: "Laufer", relationship: "primary", side: "bride" },
  { partyId: "P-040", partyLabel: "The Laufers", firstName: "Willie", lastName: "Laufer", relationship: "spouse", side: "bride" },
  { partyId: "P-041", partyLabel: "The Mckenzies", firstName: "Kelly", lastName: "Mckenzie", relationship: "primary", side: "bride" },
  { partyId: "P-041", partyLabel: "The Mckenzies", firstName: "Paul", lastName: "Mckenzie", relationship: "spouse", side: "bride" },
  { partyId: "P-042", partyLabel: "The Condermans", firstName: "Lauren", lastName: "Conderman", relationship: "primary", side: "bride" },
  { partyId: "P-042", partyLabel: "The Condermans", firstName: "David", lastName: "Conderman", relationship: "spouse", side: "bride" },
  { partyId: "P-043", partyLabel: "The Lugers", firstName: "Kim", lastName: "Luger", relationship: "primary", side: "bride" },
  { partyId: "P-043", partyLabel: "The Lugers", firstName: "Brian", lastName: "Luger", relationship: "spouse", side: "bride" },
  { partyId: "P-044", partyLabel: "The Reeveses", firstName: "Michelle", lastName: "Reeves", relationship: "primary", side: "bride" },
  { partyId: "P-044", partyLabel: "The Reeveses", firstName: "Jason", lastName: "Reeves", relationship: "spouse", side: "bride" },
  { partyId: "P-045", partyLabel: "Kendall Reeves & Duncan Strang", firstName: "Kendall", lastName: "Reeves", relationship: "primary", side: "bride" },
  { partyId: "P-045", partyLabel: "Kendall Reeves & Duncan Strang", firstName: "Duncan", lastName: "Strang", relationship: "spouse", side: "bride" },
  { partyId: "P-046", partyLabel: "The Mitchells", firstName: "Mary Beth", lastName: "Mitchell", relationship: "primary", side: "bride" },
  { partyId: "P-046", partyLabel: "The Mitchells", firstName: "Andy", lastName: "Mitchell", relationship: "spouse", side: "bride" },
  { partyId: "P-047", partyLabel: "Kate Mitchell", firstName: "Kate", lastName: "Mitchell", relationship: "primary", side: "bride" },
  { partyId: "P-048", partyLabel: "Sandy Reuther", firstName: "Sandy", lastName: "Reuther", relationship: "primary", side: "bride" },
  { partyId: "P-049", partyLabel: "The Wilcoxes (Kathy)", firstName: "Kathy", lastName: "Wilcox", relationship: "primary", side: "bride" },
  { partyId: "P-049", partyLabel: "The Wilcoxes (Kathy)", firstName: "Steve", lastName: "Wilcox", relationship: "spouse", side: "bride" },
  { partyId: "P-050", partyLabel: "The Sunvolds", firstName: "Elizabeth", lastName: "Sunvold", relationship: "primary", side: "bride" },
  { partyId: "P-050", partyLabel: "The Sunvolds", firstName: "Wilson", lastName: "Sunvold", relationship: "spouse", side: "bride" },
  { partyId: "P-051", partyLabel: "The Wilcoxes (Stephanie)", firstName: "Stephanie", lastName: "Wilcox", relationship: "primary", side: "bride" },
  { partyId: "P-051", partyLabel: "The Wilcoxes (Stephanie)", firstName: "Allison", lastName: "Wilcox", relationship: "spouse", side: "bride" },
  { partyId: "P-052", partyLabel: "Sarah Wilcox & Riley Zangs", firstName: "Sarah", lastName: "Wilcox", relationship: "primary", side: "bride" },
  { partyId: "P-052", partyLabel: "Sarah Wilcox & Riley Zangs", firstName: "Riley", lastName: "Zangs", relationship: "spouse", side: "bride" },
  { partyId: "P-053", partyLabel: "The Murrells", firstName: "Tara", lastName: "Murrell", relationship: "primary", side: "bride" },
  { partyId: "P-053", partyLabel: "The Murrells", firstName: "David", lastName: "Murrell", relationship: "spouse", side: "bride" },
  { partyId: "P-053", partyLabel: "The Murrells", firstName: "Matt", lastName: "Murrell", relationship: "plus-one", side: "bride" },
  { partyId: "P-053", partyLabel: "The Murrells", firstName: "David", lastName: "Murrell", relationship: "plus-one", side: "bride" },
  { partyId: "P-054", partyLabel: "Danica Wham", firstName: "Danica", lastName: "Wham", relationship: "primary", side: "bride" },
  { partyId: "P-055", partyLabel: "Brad Wham", firstName: "Brad", lastName: "Wham", relationship: "primary", side: "bride" },
  { partyId: "P-056", partyLabel: "Audrey Talge", firstName: "Audrey", lastName: "Talge", relationship: "primary", side: "bride" },
  { partyId: "P-057", partyLabel: "The Onyszchuks", firstName: "Barb", lastName: "Onyszchuk", relationship: "primary", side: "bride" },
  { partyId: "P-057", partyLabel: "The Onyszchuks", firstName: "Greg", lastName: "Onyszchuk", relationship: "spouse", side: "bride" },
  { partyId: "P-058", partyLabel: "Amy Barone & KJ Kentfield", firstName: "Amy", lastName: "Barone", relationship: "primary", side: "bride" },
  { partyId: "P-058", partyLabel: "Amy Barone & KJ Kentfield", firstName: "KJ", lastName: "Kentfield", relationship: "spouse", side: "bride" },
  { partyId: "P-059", partyLabel: "Kevin Kentfield", firstName: "Kevin", lastName: "Kentfield", relationship: "primary", side: "bride" },
  { partyId: "P-060", partyLabel: "The Hills", firstName: "Katie", lastName: "Hill", relationship: "primary", side: "bride" },
  { partyId: "P-060", partyLabel: "The Hills", firstName: "Jake", lastName: "Hill", relationship: "spouse", side: "bride" },
  { partyId: "P-061", partyLabel: "Christy Kentfield", firstName: "Christy", lastName: "Kentfield", relationship: "primary", side: "bride" },
  { partyId: "P-062", partyLabel: "The Merritts", firstName: "Lauren", lastName: "Merritt", relationship: "primary", side: "bride" },
  { partyId: "P-062", partyLabel: "The Merritts", firstName: "Hayden", lastName: "Merritt", relationship: "spouse", side: "bride" },
  { partyId: "P-063", partyLabel: "The Montgomerys", firstName: "Kennedy", lastName: "Montgomery", relationship: "primary", side: "bride" },
  { partyId: "P-063", partyLabel: "The Montgomerys", firstName: "Zach", lastName: "Montgomery", relationship: "spouse", side: "bride" },
  { partyId: "P-064", partyLabel: "The Matchells", firstName: "Natalie", lastName: "Matchell", relationship: "primary", side: "bride" },
  { partyId: "P-064", partyLabel: "The Matchells", firstName: "Josh", lastName: "Matchell", relationship: "spouse", side: "bride" },
  { partyId: "P-065", partyLabel: "The Wentzes", firstName: "Frances", lastName: "Wentz", relationship: "primary", side: "bride" },
  { partyId: "P-065", partyLabel: "The Wentzes", firstName: "Vance", lastName: "Wentz", relationship: "spouse", side: "bride" },
  { partyId: "P-066", partyLabel: "The Wolfs", firstName: "Taylor", lastName: "Wolf", relationship: "primary", side: "bride" },
  { partyId: "P-066", partyLabel: "The Wolfs", firstName: "Brock", lastName: "Wolf", relationship: "spouse", side: "bride" },
  { partyId: "P-067", partyLabel: "The Tylers", firstName: "Zoe", lastName: "Tyler", relationship: "primary", side: "bride" },
  { partyId: "P-067", partyLabel: "The Tylers", firstName: "Mitchell", lastName: "Tyler", relationship: "spouse", side: "bride" },
  { partyId: "P-068", partyLabel: "Gabrielle Lintner", firstName: "Gabrielle", lastName: "Lintner", relationship: "primary", side: "bride" },
  { partyId: "P-069", partyLabel: "Caroline Shannon & Corben Powell", firstName: "Caroline", lastName: "Shannon", relationship: "primary", side: "bride" },
  { partyId: "P-069", partyLabel: "Caroline Shannon & Corben Powell", firstName: "Corben", lastName: "Powell", relationship: "spouse", side: "bride" },
  { partyId: "P-070", partyLabel: "Sidney Schneider & John Guzman", firstName: "Sidney", lastName: "Schneider", relationship: "primary", side: "bride" },
  { partyId: "P-070", partyLabel: "Sidney Schneider & John Guzman", firstName: "John", lastName: "Guzman", relationship: "spouse", side: "bride" },
  { partyId: "P-071", partyLabel: "Emily Webb & Christian Albrecht", firstName: "Emily", lastName: "Webb", relationship: "primary", side: "bride" },
  { partyId: "P-071", partyLabel: "Emily Webb & Christian Albrecht", firstName: "Christian", lastName: "Albrecht", relationship: "spouse", side: "bride" },
  { partyId: "P-072", partyLabel: "The Robertsons", firstName: "Emery", lastName: "Robertson", relationship: "primary", side: "bride" },
  { partyId: "P-072", partyLabel: "The Robertsons", firstName: "Jack", lastName: "Robertson", relationship: "spouse", side: "bride" },
  { partyId: "P-073", partyLabel: "The Burditts", firstName: "Addyson", lastName: "Burditt", relationship: "primary", side: "bride" },
  { partyId: "P-073", partyLabel: "The Burditts", firstName: "Nathan", lastName: "Burditt", relationship: "spouse", side: "bride" },
  { partyId: "P-074", partyLabel: "The Longs", firstName: "Abby", lastName: "Long", relationship: "primary", side: "bride" },
  { partyId: "P-074", partyLabel: "The Longs", firstName: "Will", lastName: "Long", relationship: "spouse", side: "bride" },
  { partyId: "P-075", partyLabel: "The Cophers", firstName: "Morgan", lastName: "Copher", relationship: "primary", side: "bride" },
  { partyId: "P-075", partyLabel: "The Cophers", firstName: "Jack", lastName: "Copher", relationship: "spouse", side: "bride" },
  { partyId: "P-076", partyLabel: "Audrey Holland", firstName: "Audrey", lastName: "Holland", relationship: "primary", side: "bride" },
  { partyId: "P-077", partyLabel: "Morgan Judy", firstName: "Morgan", lastName: "Judy", relationship: "primary", side: "bride" },
  { partyId: "P-078", partyLabel: "Brooke Rosen", firstName: "Brooke", lastName: "Rosen", relationship: "primary", side: "bride" },
  { partyId: "P-079", partyLabel: "The Webbs", firstName: "Laurie", lastName: "Webb", relationship: "primary", side: "bride" },
  { partyId: "P-079", partyLabel: "The Webbs", firstName: "Trent", lastName: "Webb", relationship: "spouse", side: "bride" },
  { partyId: "P-080", partyLabel: "The Pyles", firstName: "Lynette", lastName: "Pyle", relationship: "primary", side: "bride" },
  { partyId: "P-080", partyLabel: "The Pyles", firstName: "Mark", lastName: "Pyle", relationship: "spouse", side: "bride" },
  { partyId: "P-081", partyLabel: "Maggie Pyle & Devin Fix", firstName: "Maggie", lastName: "Pyle", relationship: "primary", side: "bride" },
  { partyId: "P-081", partyLabel: "Maggie Pyle & Devin Fix", firstName: "Devin", lastName: "Fix", relationship: "spouse", side: "bride" },
  { partyId: "P-082", partyLabel: "Caroline Kohring & Spencer Mustoe", firstName: "Caroline", lastName: "Kohring", relationship: "primary", side: "bride" },
  { partyId: "P-082", partyLabel: "Caroline Kohring & Spencer Mustoe", firstName: "Spencer", lastName: "Mustoe", relationship: "spouse", side: "bride" },
  { partyId: "P-083", partyLabel: "Morgan Clausen", firstName: "Morgan", lastName: "Clausen", relationship: "primary", side: "bride" },
  { partyId: "P-084", partyLabel: "The Todds", firstName: "Emma", lastName: "Todd", relationship: "primary", side: "bride" },
  { partyId: "P-084", partyLabel: "The Todds", firstName: "Justin", lastName: "Todd", relationship: "spouse", side: "bride" },
  { partyId: "P-085", partyLabel: "The Kurths", firstName: "Carolyn", lastName: "Kurth", relationship: "primary", side: "bride" },
  { partyId: "P-085", partyLabel: "The Kurths", firstName: "Tom", lastName: "Kurth", relationship: "spouse", side: "bride" },
  { partyId: "P-086", partyLabel: "Mackenzie Sweat", firstName: "Mackenzie", lastName: "Sweat", relationship: "primary", side: "bride" },
  { partyId: "P-087", partyLabel: "Sophie Tulp", firstName: "Sophie", lastName: "Tulp", relationship: "primary", side: "bride" },
  { partyId: "P-088", partyLabel: "Katie Spradling", firstName: "Katie", lastName: "Spradling", relationship: "primary", side: "bride" },
  { partyId: "P-089", partyLabel: "Piper Cohen", firstName: "Piper", lastName: "Cohen", relationship: "primary", side: "bride" },
  { partyId: "P-090", partyLabel: "The Bartletts", firstName: "Maddie", lastName: "Bartlett", relationship: "primary", side: "bride" },
  { partyId: "P-090", partyLabel: "The Bartletts", firstName: "Alex", lastName: "Bartlett", relationship: "spouse", side: "bride" },
  { partyId: "P-091", partyLabel: "The Roses", firstName: "Morgan", lastName: "Rose", relationship: "primary", side: "bride" },
  { partyId: "P-091", partyLabel: "The Roses", firstName: "Lori", lastName: "Rose", relationship: "spouse", side: "bride" },
  { partyId: "P-092", partyLabel: "The Sweats", firstName: "Susan", lastName: "Sweat", relationship: "primary", side: "bride" },
  { partyId: "P-092", partyLabel: "The Sweats", firstName: "Greg", lastName: "Sweat", relationship: "spouse", side: "bride" },
  { partyId: "P-093", partyLabel: "Bobby Davis", firstName: "Bobby", lastName: "Davis", relationship: "primary", side: "bride" },
  { partyId: "P-094", partyLabel: "The O'Rears", firstName: "Chuck", lastName: "O'Rear", relationship: "primary", side: "bride" },
  { partyId: "P-094", partyLabel: "The O'Rears", firstName: "Michelle", lastName: "O'Rear", relationship: "spouse", side: "bride" },
  { partyId: "P-095", partyLabel: "Jamie Johnston", firstName: "Jamie", lastName: "Johnston", relationship: "primary", side: "bride" },
  { partyId: "P-096", partyLabel: "The Gardners", firstName: "Eric", lastName: "Gardner", relationship: "primary", side: "bride" },
  { partyId: "P-096", partyLabel: "The Gardners", firstName: "Jen", lastName: "Gardner", relationship: "spouse", side: "bride" },
  { partyId: "P-097", partyLabel: "Trenton Sadrakula", firstName: "Trenton", lastName: "Sadrakula", relationship: "primary", side: "groom" },
  { partyId: "P-098", partyLabel: "The Sadrakulas (Missy)", firstName: "Missy", lastName: "Sadrakula", relationship: "primary", side: "groom" },
  { partyId: "P-098", partyLabel: "The Sadrakulas (Missy)", firstName: "Sophie", lastName: "Sadrakula", relationship: "spouse", side: "groom" },
  { partyId: "P-099", partyLabel: "Evan Sadrakula & Jessica Nachtsheim", firstName: "Evan", lastName: "Sadrakula", relationship: "primary", side: "groom" },
  { partyId: "P-099", partyLabel: "Evan Sadrakula & Jessica Nachtsheim", firstName: "Jessica", lastName: "Nachtsheim", relationship: "spouse", side: "groom" },
  { partyId: "P-100", partyLabel: "John Sadrakula", firstName: "John", lastName: "Sadrakula", relationship: "primary", side: "groom" },
  { partyId: "P-101", partyLabel: "The Hinkles", firstName: "Rich", lastName: "Hinkle", relationship: "primary", side: "groom" },
  { partyId: "P-101", partyLabel: "The Hinkles", firstName: "Kathy", lastName: "Hinkle", relationship: "spouse", side: "groom" },
  { partyId: "P-102", partyLabel: "The Sadrakulas (Robert)", firstName: "Robert", lastName: "Sadrakula", relationship: "primary", side: "groom" },
  { partyId: "P-102", partyLabel: "The Sadrakulas (Robert)", firstName: "Carol", lastName: "Sadrakula", relationship: "spouse", side: "groom" },
  { partyId: "P-103", partyLabel: "The Smiths", firstName: "Stephanie", lastName: "Smith", relationship: "primary", side: "groom" },
  { partyId: "P-103", partyLabel: "The Smiths", firstName: "Larry", lastName: "Smith", relationship: "spouse", side: "groom" },
  { partyId: "P-103", partyLabel: "The Smiths", firstName: "Hannah", lastName: "Smith", relationship: "plus-one", side: "groom" },
  { partyId: "P-103", partyLabel: "The Smiths", firstName: "Chase", lastName: "Smith", relationship: "child", side: "groom" },
  { partyId: "P-104", partyLabel: "Ryan Finazzo & Family", firstName: "Ryan", lastName: "Finazzo", relationship: "primary", side: "groom" },
  { partyId: "P-104", partyLabel: "Ryan Finazzo & Family", firstName: "Kristen", lastName: "Richards", relationship: "spouse", side: "groom" },
  { partyId: "P-104", partyLabel: "Ryan Finazzo & Family", firstName: "Brooklyn", lastName: "Finazzo", relationship: "child", side: "groom" },
  { partyId: "P-104", partyLabel: "Ryan Finazzo & Family", firstName: "Travis", lastName: "Finazzo", relationship: "child", side: "groom" },
  { partyId: "P-105", partyLabel: "The Finazzos", firstName: "Nick", lastName: "Finazzo", relationship: "primary", side: "groom" },
  { partyId: "P-105", partyLabel: "The Finazzos", firstName: "Brenna", lastName: "Finazzo", relationship: "spouse", side: "groom" },
  { partyId: "P-105", partyLabel: "The Finazzos", firstName: "Elliot", lastName: "Finazzo", relationship: "child", side: "groom" },
  { partyId: "P-106", partyLabel: "The Stradas", firstName: "Susie", lastName: "Strada", relationship: "primary", side: "groom" },
  { partyId: "P-106", partyLabel: "The Stradas", firstName: "Brosie", lastName: "Strada", relationship: "spouse", side: "groom" },
  { partyId: "P-106", partyLabel: "The Stradas", firstName: "Lauren", lastName: "Strada", relationship: "child", side: "groom" },
  { partyId: "P-106", partyLabel: "The Stradas", firstName: "Alyssa", lastName: "Strada", relationship: "child", side: "groom" },
  { partyId: "P-107", partyLabel: "The Sadrakulas (Mike)", firstName: "Mike", lastName: "Sadrakula", relationship: "primary", side: "groom" },
  { partyId: "P-107", partyLabel: "The Sadrakulas (Mike)", firstName: "Melissa", lastName: "Sadrakula", relationship: "spouse", side: "groom" },
  { partyId: "P-107", partyLabel: "The Sadrakulas (Mike)", firstName: "Quinn", lastName: "Sadrakula", relationship: "plus-one", side: "groom" },
  { partyId: "P-107", partyLabel: "The Sadrakulas (Mike)", firstName: "Grant", lastName: "Sadrakula", relationship: "plus-one", side: "groom" },
  { partyId: "P-107", partyLabel: "The Sadrakulas (Mike)", firstName: "Beck", lastName: "Sadrakula", relationship: "child", side: "groom" },
  { partyId: "P-107", partyLabel: "The Sadrakulas (Mike)", firstName: "Gage", lastName: "Sadrakula", relationship: "child", side: "groom" },
  { partyId: "P-108", partyLabel: "Linda Benson", firstName: "Linda", lastName: "Benson", relationship: "primary", side: "groom" },
  { partyId: "P-109", partyLabel: "The Stutheits", firstName: "Michelle", lastName: "Stutheit", relationship: "primary", side: "groom" },
  { partyId: "P-109", partyLabel: "The Stutheits", firstName: "Dave", lastName: "Stutheit", relationship: "spouse", side: "groom" },
  { partyId: "P-110", partyLabel: "The Nachtsheims (Patrick)", firstName: "Patrick", lastName: "Nachtsheim", relationship: "primary", side: "groom" },
  { partyId: "P-110", partyLabel: "The Nachtsheims (Patrick)", firstName: "Jade", lastName: "Nachtsheim", relationship: "spouse", side: "groom" },
  { partyId: "P-111", partyLabel: "The Nachtsheims (Stephen)", firstName: "Stephen", lastName: "Nachtsheim", relationship: "primary", side: "groom" },
  { partyId: "P-111", partyLabel: "The Nachtsheims (Stephen)", firstName: "Tessa", lastName: "Nachtsheim", relationship: "spouse", side: "groom" },
  { partyId: "P-112", partyLabel: "The Elliots", firstName: "Joann", lastName: "Elliot", relationship: "primary", side: "groom" },
  { partyId: "P-112", partyLabel: "The Elliots", firstName: "Dan", lastName: "Elliot", relationship: "spouse", side: "groom" },
  { partyId: "P-113", partyLabel: "Joel Zuniga", firstName: "Joel", lastName: "Zuniga", relationship: "primary", side: "groom" },
  { partyId: "P-114", partyLabel: "The Ramirezes", firstName: "Zach", lastName: "Ramirez", relationship: "primary", side: "groom" },
  { partyId: "P-114", partyLabel: "The Ramirezes", firstName: "Izzy", lastName: "Ramirez", relationship: "spouse", side: "groom" },
  { partyId: "P-115", partyLabel: "The Kumps", firstName: "Charles", lastName: "Kump", relationship: "primary", side: "groom" },
  { partyId: "P-115", partyLabel: "The Kumps", firstName: "Serena", lastName: "Kump", relationship: "spouse", side: "groom" },
  { partyId: "P-116", partyLabel: "Ramon Conejo", firstName: "Ramon", lastName: "Conejo", relationship: "primary", side: "groom" },
  { partyId: "P-117", partyLabel: "The Lucases", firstName: "Clayton", lastName: "Lucas", relationship: "primary", side: "groom" },
  { partyId: "P-117", partyLabel: "The Lucases", firstName: "Heather", lastName: "Lucas", relationship: "spouse", side: "groom" },
  { partyId: "P-118", partyLabel: "Natasha Stansberry", firstName: "Natasha", lastName: "Stansberry", relationship: "primary", side: "groom" },
  { partyId: "P-119", partyLabel: "Teo Subasic", firstName: "Teo", lastName: "Subasic", relationship: "primary", side: "groom" },
  { partyId: "P-120", partyLabel: "The Subasics", firstName: "Tony", lastName: "Subasic", relationship: "primary", side: "groom" },
  { partyId: "P-120", partyLabel: "The Subasics", firstName: "Audrey", lastName: "Subasic", relationship: "spouse", side: "groom" },
  { partyId: "P-121", partyLabel: "Paulina Subasic", firstName: "Paulina", lastName: "Subasic", relationship: "primary", side: "groom" },
  { partyId: "P-122", partyLabel: "Jaxen Conejo", firstName: "Jaxen", lastName: "Conejo", relationship: "primary", side: "groom" },
  { partyId: "P-123", partyLabel: "The Mikesics", firstName: "Andy", lastName: "Mikesic", relationship: "primary", side: "groom" },
  { partyId: "P-123", partyLabel: "The Mikesics", firstName: "John", lastName: "Mikesic", relationship: "spouse", side: "groom" },
  { partyId: "P-124", partyLabel: "The Schreifelses", firstName: "Jacob", lastName: "Schreifels", relationship: "primary", side: "groom" },
  { partyId: "P-124", partyLabel: "The Schreifelses", firstName: "Jordy", lastName: "Schreifels", relationship: "spouse", side: "groom" },
  { partyId: "P-125", partyLabel: "Brandon Twidwell", firstName: "Brandon", lastName: "Twidwell", relationship: "primary", side: "groom" },
  { partyId: "P-126", partyLabel: "Danny Mcdonald & Family", firstName: "Danny", lastName: "Mcdonald", relationship: "primary", side: "groom" },
  { partyId: "P-126", partyLabel: "Danny Mcdonald & Family", firstName: "Tyler", lastName: "Cerrato", relationship: "spouse", side: "groom" },
  { partyId: "P-126", partyLabel: "Danny Mcdonald & Family", firstName: "Katie", lastName: "Cerrato", relationship: "plus-one", side: "groom" },
  { partyId: "P-127", partyLabel: "The Yateses", firstName: "Meghan", lastName: "Yates", relationship: "primary", side: "groom" },
  { partyId: "P-127", partyLabel: "The Yateses", firstName: "Dakotah", lastName: "Yates", relationship: "spouse", side: "groom" },
  { partyId: "P-128", partyLabel: "The Carlins", firstName: "Margaret", lastName: "Carlin", relationship: "primary", side: "groom" },
  { partyId: "P-128", partyLabel: "The Carlins", firstName: "Jeffrey", lastName: "Carlin", relationship: "spouse", side: "groom" },
  { partyId: "P-129", partyLabel: "Jeffrey Carlin Jr & Brianna Carlin", firstName: "Jeffrey", lastName: "Carlin Jr", relationship: "primary", side: "groom" },
  { partyId: "P-129", partyLabel: "Jeffrey Carlin Jr & Brianna Carlin", firstName: "Brianna", lastName: "Carlin", relationship: "spouse", side: "groom" },
  { partyId: "P-130", partyLabel: "The Jacobses", firstName: "Jordyn", lastName: "Jacobs", relationship: "primary", side: "groom" },
  { partyId: "P-130", partyLabel: "The Jacobses", firstName: "Dallas", lastName: "Jacobs", relationship: "spouse", side: "groom" },
];

export function getRosterGuests(): GuestRow[] {
  return GUEST_ROSTER.map((row, i) => ({ ...row, rowIndex: i + 2 }));
}
